### ISSUE TITLE
Receiving JSON error on sensor. 

### ISSUE THREAD

**Issue by mstein04** [PaesslerAG/PRTGScheduler#19]
Manually executing the script doesn't provide any sort of errors.  I made sure to go through the install doc multiple times and everything appears to be set correctly.  Still receiving the following error on the sensor. XML: The returned XML does not match the expected schema. (code: PE233) -- JSON: The returned JSON does not match the expected structure (Invalid JSON.). (code: PE231)

**Comment by stephanlinke** [comment]
Did you enable the debug mode in the app settings prior to executing it? The following was also considered: https://kb.paessler.com/en/topic/71356-guide-for-powershell-based-custom-sensors ?

**Comment by mstein04** [comment]
Debug was enabled.  Going through this made me rethink how it was setup.  I had placed the powershell script into the EXEML folder, needed to be in the EXE folder.  Working now! Thanks!

**Comment by mafer0410** [comment]
Hi, donde se agrega el mantenimiento?

**Comment by mafer0410** [comment]
hello, where is the maintenance status configured?
